# Generated by Django 4.2.4 on 2023-08-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookah.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField(max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('discounts', models.FloatField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookah.categoria')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookah.model')),
            ],
        ),
    ]
